### ISSUE TITLE
[Feature Request] An automation scripts mechanism to automate some actions

### ISSUE THREAD

**Issue by StrayDragon** [StrayDragon/dragon#5]
> Is your feature request related to a problem? Please describe.

Like bash scripts to batch some actions.

> Describe the solution you'd like

For example, you can use it to reinstall some applications quickly... 
If you use some interactive CLI apps, like `ipython`, 'ipdb', `mycli`, `pgcli`, `iredis`, etc. normally, you may need install them manually.
but now use the sub-command and customized scripts to solved it easily
```toml
# reinstall.toml
# User define
[required]
executable = 'pipx'
cmd = 'pipx install $'

[install]
list = ['ipython','ipdb','mycli']
```

```bash
$ dg install --from=reinstall.toml
```

> Notes

Configuration file type and options also need to look for a good way to express idea and goal clearly.
